[build]
target = "x86_64-exorust.json"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-exorust]
runner = "qemu-system-x86_64 -drive format=raw,file="
